#!/bin/bash

options=(
	style=round
	width=2
	hidpi=on
	active_color=0xffbd93f9
	inactive_color=0xff414550
)

borders "${options[@]}"
borders order=above 
# has to do this or else the border 
# wont work; read more here: 
# https://github.com/FelixKratz/JankyBorders/issues/37#issuecomment-1871262622
